# Generated by Django 4.1.3 on 2022-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_contact_patient_contact_hello'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact_hello',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'Sophomore')], default='M', max_length=2),
        ),
    ]
