# Generated by Django 4.1.3 on 2022-12-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='contact2',
            new_name='guardian_contact',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='guardian',
            new_name='guardian_name',
        ),
    ]
