# Generated by Django 4.1.3 on 2022-12-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_rename_contact2_patient_guardian_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medical_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
